<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="css/cocktails.css">
</head>
<body>
    
    <?php include 'vues/nav.phtml'; ?>
    <?php include 'vues/header.phtml'; ?>

    <!-- DÉBUT DU MAIN -->
    <main>

        <!-- DÉBUT DE LA SECTION LISTE DES COCKTAILS -->
        <section id="add_cocktail" class="mt-5">
            <div class="container">
            <form action="" method="POST">
                <div class="row">

                        <?php if($message) : ?>
                            <div class="col-12">
                                <div class="alert alert-<?=$messageType?>" role="alert">
                                    <?=$message?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <div class="col-6">
                            
                            <!-- FORMULAIRE ICI -->
                            <div class="mb-3">
                                <label for="name" class="form-label">Nom du cocktail</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Mojito" required value="Test">
                            </div>

                            <div class="mb-3">
                                <label for="id_family" class="form-label">Famille</label>
                                <select class="form-select" name="id_family" id="id_family" required>
                                    <option value="" disabled selected>Sélectionnez</option>
                                    <?php foreach($families as $family) : ?>
                                        <option value="<?=$family['id']?>"><?=$family['name']?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>   

                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea name="description" id="description" class="form-control" rows="10" placeholder="Lorem ipsum dolor sit amet" required>
                                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit dolorum perferendis autem provident ipsam odit facere laborum rem eius! Natus atque veritatis consectetur architecto fugiat iste consequatur sapiente! Corporis, culpa.
                                </textarea>
                            </div>                           
                        </div>

                        <div class="col-6">
                            <div class="mb-3">
                                <label for="image" class="form-label">Nom du fichier image</label>
                                <input type="text" class="form-control" name="image" id="image" placeholder="mojito.jpg" required value="test.jpg">
                            </div>
                            
                            <div class="mb-3">
                                <label for="year" class="form-label">Année</label>
                                <input type="number" class="form-control" name="year" id="year" placeholder="1538" required value="9999">
                            </div>
                            
                            <div class="mb-3">
                                <label for="price" class="form-label">Prix</label>
                                <input type="number" step="0.01" class="form-control" name="price" id="price" placeholder="9.99" required value="9999.99">
                            </div>    
                            
                            <div class="mb-3 text-end">
                                <input type="submit" value="Enregistrer" class="btn btn-primary">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </section>
        <!-- FIN DE LA SECTION LISTE DES COCKTAILS -->
        
    </main>
    <!-- FIN DU MAIN -->
    
    <?php include 'vues/footer.phtml'; ?>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>    
</body>
</html>