<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="css/cocktails.css">
</head>
<body>
    
    <?php include 'vues/nav.phtml'; ?>
    <?php include 'vues/header.phtml'; ?>

    <!-- DÉBUT DU MAIN -->
    <main>

        <!-- DÉBUT DE LA SECTION LISTE DES COCKTAILS -->
        <section id="list_cocktails" class="mt-5">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">


                        <table class="table table-sm table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nom</th>
                                    <th>Famille</th>
                                    <th>Description</th>
                                    <th>Prix</th>
                                    <th>Année</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($cocktails as $cocktail): ?>
                                <tr>
                                    <td><?=$cocktail['id']?></td>
                                    <td><?=$cocktail['name']?></td>
                                    <td><?=$cocktail['family_name']?></td>
                                    <td><?=$cocktail['description']?></td>
                                    <td><?=$cocktail['price']?>€</td>
                                    <td><?=$cocktail['year']?></td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="edit_cocktail.php?id=<?=$cocktail['id']?>" class="btn btn-primary">Éditer</a>
                                            <a href="delete_cocktail.php?id<?=$cocktail['id']?>" class="btn btn-danger">Supprimer</a>
                                        </div>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>


                        
                    </div>
                </div>
            </div>
        </section>
        <!-- FIN DE LA SECTION LISTE DES COCKTAILS -->
        
    </main>
    <!-- FIN DU MAIN -->
    
    <?php include 'vues/footer.phtml'; ?>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>    
</body>
</html>