<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="css/cocktails.css">
</head>
<body>

    <?php include 'vues/nav.phtml'; ?>
    <?php include 'vues/header.phtml'; ?>



    <!-- DÉBUT DU MAIN -->
    <main>

        <!-- DÉBUT DE LA SECTION LISTE DES COCKTAILS -->
        <section id="list_cocktails" class="mt-5">
            <div class="container">
                <div class="row">
                    <!-- pour la boucle, il faut répéter toute la div "col-4"-->
                    <?php foreach($cocktails as $cocktail) : ?>
                    <div class="col-sm-6 col-md-4 col-xl-3 mb-3">
                        <article class="card cocktail">
                            <a href="detail_cocktail.php?id=<?=$cocktail['id']?>">
                                <img class="card-img-top" src="images/cocktails/<?=$cocktail['image']?>" alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title"><?=$cocktail['name']?></h4>
                                <p class="card-text"><?=$cocktail['description']?></p>
                            </div>
                        </article>
                    </div>
                    <?php endforeach; ?>
                    <!-- Fin de la boucle -->
                </div>
            </div>
        </section>
        <!-- FIN DE LA SECTION LISTE DES COCKTAILS -->
        
    </main>
    <!-- FIN DU MAIN -->
    
    <?php include 'vues/footer.phtml'; ?>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>    
</body>
</html>