    <!-- DÉBUT DE LA NAV -->
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="container">

            <a class="navbar-brand" href="index.php">Mister cocktail</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="add_cocktail.php">Ajouter un cocktail</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="back_office.php">Back-office</a>
                    </li>                    
                </ul>
            </div>
        </div>
        </nav>
    <!-- FIN DE LA NAV -->